# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tts 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "tts"
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Yiling Cao"]
  s.date = "2015-08-18"
  s.description = "easy way to generate a voice file based on text prvoided."
  s.summary = "a text to speech file tool"
  s.email = "yiling.cao@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  
  s.executables   = ["tts", "text2mp3"]
  s.files         =  `git ls-files`.split($/)

  s.homepage = "http://github.com/c2h2/tts"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.6"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.6"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.6"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
  end
end

